---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pstuianc/public_html/portfolio/hasnain/dev/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp portfolio-details.html $DEPLOYPATH